# Token=================================================================
token:
  tokenSigningKey: "admin-server"                 # 设置Token生成加密的签名
  tokenExpiresDuration: 24 * 60 * 60              # 设置Token过期时间(单位: s)
  tokenRefreshDuration: 60 * 60                   # 设置Token更新时间
# Logs==================================================================
log:
  filename: "logs/log.txt"
  maxSize: 500  # megabytes
  maxBackups: 3
  maxAge: 28
  compress: true
# Redis=================================================================
redis:
